services:
  server:
    container_name: afa-server
    build:
      context: ./backend
      target: production

    environment:
      - DEBUG=${DEBUG:-False}
      - SUPERUSER_USERNAME=${SUPERUSER_USERNAME}
      - SUPERUSER_EMAIL=${SUPERUSER_EMAIL}
      - SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}

      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - media-data:/app/media
      - static-data:/app/staticfiles
    restart: unless-stopped

  # Caddy
  frontend: 
    build:
      context: ./frontend
      target: production

    ports:
      - "8080:80"
      #- "80:80"
      #- "443:443"

    depends_on:
      - server
    
    volumes:
      - media-data:/media:ro  # The left path is coherent with the path in the Caddyfile.
      
      - caddy-data:/data      # These 2 volumes are advised to keep TCL certif among other 
      - caddy-config:/config  # caddy files and config.
      - static-data:/srv/static:ro

    restart: unless-stopped

  db:
    image: postgres:18
    container_name: afa-postgres-db

    volumes:
      - db-data:/var/lib/postgresql

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    expose:
      - "5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    
    restart: unless-stopped

volumes:
  db-data:
  media-data: # created to mount the data in the backend container
  caddy-data:
  caddy-config:
  static-data:

# Possible to update to secrets in production later (.env is currently used)