services:
  server:
    container_name: afa-server
    build:
      # Server Dockefile emplacement
      context: ./backend
    volumes:
      # bind mount enabling modifications on the host
      - .:/project
      # - ./frontend/src:/project/frontend	
    ports:
      - 8000:8000
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      db:
        condition: service_healthy

  client:
    container_name: afa-client
    build:
      # Frontend Dockefile emplacement
      context: ./frontend
    volumes:
      # bind mount enabling modifications on the host 
      # (app is not the same as for the server) since it is a different container
      - ./frontend:/app
      - /app/node_modules # to save in container modifications
    ports:
      - "5173:5173"
    environment:
      # to refresh when modified
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server 

  db:
    image: postgres:18
    container_name: afa-postgres-db
    restart: always
  
    volumes:
      # db-data is on the host but managed by docker
      # /var/lib/postgresql allows the volume to persist
      - db-data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - 5432
    healthcheck:
      #test: ["CMD", "pg_isready"]
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
  node_modules:

# Useful for production (in dev, the global .env is used)
# secrets: