# Generated by Django 6.0.2 on 2026-08-03 14:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('type', models.CharField(choices=[('poem', 'Poem'), ('essay', 'Essay'), ('quote', 'Quote'), ('commentary', 'Commentary'), ('novel', 'Novel'), ('music', 'Music'), ('graphic', 'Graphic')], max_length=50)),
                ('content', models.TextField()),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
