# Generated by Django 6.0.2 on 2026-08-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afa_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='created_at',
        ),
        migrations.AddField(
            model_name='document',
            name='language',
            field=models.CharField(choices=[('fr', 'French'), ('en', 'English')], default='en', max_length=50),
        ),
    ]
