# Generated by Django 6.0.2 on 2026-08-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afa_app', '0002_remove_document_created_at_document_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('poems', 'Poems'), ('essays', 'Essays'), ('quotes', 'Quotes'), ('commentarys', 'Commentarys'), ('novels', 'Novels'), ('musics', 'Musics'), ('graphics', 'Graphics')], max_length=50),
        ),
    ]
