# Generated by Django 6.0.2 on 2026-08-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afa_app', '0004_remove_document_content_remove_document_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttranslation',
            name='slug',
            field=models.SlugField(editable=False, max_length=200),
        ),
    ]
