# Generated by Django 6.0.2 on 2026-08-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afa_app', '0005_alter_documenttranslation_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttranslation',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
