# Generated by Django 6.0.2 on 2026-08-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afa_app', '0006_documenttranslation_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('poems', 'Poems'), ('essays', 'Essays'), ('quotes', 'Quotes'), ('commentarys', 'Commentarys'), ('novels', 'Novels'), ('musics', 'Musics'), ('graphic', 'Graphic')], max_length=50),
        ),
    ]
