# Generated by Django 6.0.2 on 2026-08-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afa_app', '0007_contact_alter_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='media',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
    ]
