# Generated by Django 6.0.2 on 2026-08-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afa_app', '0008_document_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='media',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
