name: Deploy to Hetzner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Deploy files
        uses: burnett01/rsync-deployments@v8
        with:
          switches: -avzr --delete --exclude='.git/' --exclude='.github/' --exclude='.devcontainer/' --exclude='.vscode/' --exclude='.env*' --exclude='README.md' --exclude='compose.yml'
          path: ./
          remote_path: /home/${{ secrets.DEPLOYMENT_USERNAME }}/app/
          remote_host: ${{ secrets.DEPLOYMENT_HOST }}
          remote_port: 22
          remote_user: ${{ secrets.DEPLOYMENT_USERNAME }}
          remote_key: ${{ secrets.DEPLOYMENT_KEY }}

      - name: Restart application
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DEPLOYMENT_HOST }}
          username: ${{ secrets.DEPLOYMENT_USERNAME }}
          key: ${{ secrets.DEPLOYMENT_KEY }}
          port: 22
          script: |
            cd ~/app
            docker compose -f compose.prod.yml --env-file .env.prod up -d --build