name: Deploy to Hetzner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOYMENT_KEY }}" > ~/.ssh/id_ed25519_git_deployment
          chmod 600 ~/.ssh/id_ed25519_git_deployment
          ssh-keyscan -p 22 -t ed25519 ${{ secrets.DEPLOYMENT_HOST }} >> ~/.ssh/known_hosts
      
      - name: Inspect source
        run: |
          pwd
          ls -la
          find . -maxdepth 1 -type f -printf '%f\n' | sort

      - name: Deploy to Hetzner
        run: |
          rsync -az -M--debug=FILTER --delete --itemize-changes \
          -f'-p .env.prod' \
          -f'- .env.example' \
          -e "ssh -i ~/.ssh/id_ed25519_git_deployment -p 22" \
          ./ ${{ secrets.DEPLOYMENT_USERNAME }}@${{ secrets.DEPLOYMENT_HOST }}:~/app/
          
          ssh -i ~/.ssh/id_ed25519_git_deployment \
            -p 22 \
            ${{ secrets.DEPLOYMENT_USERNAME }}@${{ secrets.DEPLOYMENT_HOST }} \
            'cd ~/app && docker compose -f compose.prod.yml --env-file .env.prod up -d --build'